# Generated by Django 4.2.11 on 2024-04-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0004_remove_comment_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
